### PR TITLE
Friendship v1

### PR DESCRIPTION
**Pull request by GzimAsani**
In this millstone, the logged-in user is able to do all the following:

- A user is able to see all other users
- A user can like/comment other users posts/comments
- A user can create a comment
- A user can send friends requests to other users
- A user can see his friends
- A user can see all friends requests towards him

### CODE REVIEW

**Review by voscarmv — CHANGES_REQUESTED** [review]
# Impressive work, team. 💻 👀 ✨ 

## However, there are some changes required 👀 🧰 🔨 🔧 

- When I click once on the 'Add Friend' button, in the Users list page, the button doesn't update: it still shows the 'Add User' text. It is only until I click on it a second time that the page updates and shows me an error message "Request already sent", and updates the button to "Delete request" Please fix this.
- When I receive a friendship request from another user, the button from the other user says "Delete request" instead of  "Accept friendship". This is confusing, please fix it.
- I can't really accept friendship requests because when I click the button, it only deletes the friendship request I received, instead of accepting it.
- Please add some integration tests with something like Capybara, so that you may automatically test login, posting, and friendship functionality.

**[OPTIONAL]**

- Please take some time to read about the N+1 problem and implement a solution in your project: https://semaphoreci.com/blog/2017/08/09/faster-rails-eliminating-n-plus-one-queries.html
- Also, make sure that you only use the needed routes for your models. For example, friendships: they don't require editing, so it's best to exclude that route from the config.

### Submit these changes and request a new code review! 😄 👍 

### Questions or comments? Reach me on [Twitter](https://twitter.com/voscarmv) or [LinkedIn](https://linkedin.com/in/oscar-mier) 🧑‍💻🗨️🧑‍💻 
# Happy Hacking! 🧠 ⌨️ 🖱️ 🖥️

**Review by voscarmv — CHANGES_REQUESTED** [review]
# Nice work so far, team. 👍 
## However, there are some changes required 👀 🧰 🔨 🔧 

- In the change you made (https://github.com/GzimAsani/ror-social-scaffold/pull/2/commits/1357154910e2f9b85310fdd17898bc769044e9d3), I still don't see any option to "Accept friend". In the example I'm trying to carry out, I sent a friend request to user Oscar. But when I log in as Oscar to accept the friend request, I see this in the All Users page:
image

As you can see, when someone receives a friendship request, they can't accept it from that page. The user should be able to accept, **and** reject the request from the same page.

- Also, please remember to add some integration tests with something like Capybara as it's required by this stage of the project.

**[OPTIONAL]**

- Consider the same optional changes as before.

### Submit these changes and request a new code review! 😄 👍 

### Questions or comments? Reach me on [Twitter](https://twitter.com/voscarmv) or [LinkedIn](https://linkedin.com/in/oscar-mier) 🧑‍💻🗨️🧑‍💻 
# Happy Hacking! 🧠 ⌨️ 🖱️ 🖥️

**Review by voscarmv — CHANGES_REQUESTED** [review]
# Nice work so far, team. 👍 

## However, there are some changes required 👀 🧰 🔨 🔧 

- Please remember to add some integration tests with Capybara (or something similar) to the project.

### Submit these changes and request a new code review! 😄 👍 

### Questions or comments? Reach me on [Twitter](https://twitter.com/voscarmv) or [LinkedIn](https://linkedin.com/in/oscar-mier) 🧑‍💻🗨️🧑‍💻 
# Happy Hacking! 🧠 ⌨️ 🖱️ 🖥️

**Comment by GzimAsani** [comment]
I have added Integration tests with Capybara. Didn't I do it in a correct way or something?

**Comment by voscarmv** [comment]
> I have added Integration tests with Capybara. Didn't I do it in a correct way or something?

Hi @GzimAsani ,

In your rspec folder: https://github.com/GzimAsani/ror-social-scaffold/tree/friendship-v1/spec

There are only model tests. What is expected are integration tests which test the page functionality through automatic submission of forms, such as the login form, the posts form, etcetera.

If you added the tests to a different folder, please link me to it in the comments here and submit the project for a new code review. I'll try to approve it in case the tests I have specified were added and I missed them for some reason. But otherwise, please take some time to add them.

**Comment by GzimAsani** [comment]
> > I have added Integration tests with Capybara. Didn't I do it in a correct way or something?
> 
> Hi @GzimAsani ,
> 
> In your rspec folder: https://github.com/GzimAsani/ror-social-scaffold/tree/friendship-v1/spec
> 
> There are only model tests. What is expected are integration tests which test the page functionality through automatic submission of forms, such as the login form, the posts form, etcetera.
> 
> If you added the tests to a different folder, please link me to it in the comments here and submit the project for a new code review. I'll try to approve it in case the tests I have specified were added and I missed them for some reason. But otherwise, please take some time to add them.

Thank you for this clarification. I will add them!

**Comment by voscarmv** [comment]
> > > I have added Integration tests with Capybara. Didn't I do it in a correct way or something?
> > 
> > 
> > Hi @GzimAsani ,
> > In your rspec folder: https://github.com/GzimAsani/ror-social-scaffold/tree/friendship-v1/spec
> > There are only model tests. What is expected are integration tests which test the page functionality through automatic submission of forms, such as the login form, the posts form, etcetera.
> > If you added the tests to a different folder, please link me to it in the comments here and submit the project for a new code review. I'll try to approve it in case the tests I have specified were added and I missed them for some reason. But otherwise, please take some time to add them.
> 
> Thank you for this clarification. I will add them!

Excellent! Let me know if you need help witha anything else :) Happy hacking!

**Review by ebeagusamuel — APPROVED** [review]
# Project Approved :100: 
### Congratulations team :dancing_men: 
##### You have done a fantastic job on this project and in your resilience in making the changes requested of you.
##### You can proceed to the next milestone and good luck

slack(@ebeagusamuel)

**Pull request merged**
