### PR TITLE
Friendship v2

### PR DESCRIPTION
**Pull request by GzimAsani**
- Tests exists
-Styling added
- Mutual friendship function exists

### CODE REVIEW

**Review by peterrobert — CHANGES_REQUESTED** [review]
### CHANGES REQUIRED ♻️ 🛑 
Hello, @GzimAsani  very nice work I have checked your code and it seems you have implemented almost everything that is required in this milestone. 👍🏿 👏🏿 . However there is one issue that needs to be resolved before we can move on. Kindly check below.

- [ ] There seems to be a problem with your migrations. Although I have tried to check all of your code, this has prevented me to give a complete review. Let's check it out ⬇️ 
  
Screenshot from 2021-01-04 11-30-49

As you can see above it seems you have created a migration to create an existing table. Instead of this, add the columns you need to this table.  😄  
Kindly use this [article](https://guides.rubyonrails.org/active_record_migrations.html) to learn more about this.

- [ ] Your pull request message seems to have some typing errors. Kindly try and use Grammarly to help with this.

kindly fix those issues and submit your project for another review

### If you have any question kindly reach me on slack @peterrobert

### HAPPY CODING 💻

**Comment by GzimAsani** [comment]
> ### CHANGES REQUIRED  
> Hello, @GzimAsani very nice work I have checked your code and it seems you have implemented almost everything that is required in this milestone. 👍🏿 👏🏿 . However there is one issue that needs to be resolved before we can move on. Kindly check below.
> 
> * [ ]  There seems to be a problem with your migrations. Although I have tried to check all of your code, this has prevented me to give a complete review. Let's check it out arrow_down
> 
> Screenshot from 2021-01-04 11-30-49
> 
> As you can see above it seems you have created a migration to create an existing table. Instead of this, add the columns you need to this table. 
> Kindly use this [article](https://guides.rubyonrails.org/active_record_migrations.html) to learn more about this.
> 
> * [ ]  Your pull request message seems to have some typing errors. Kindly try and use Grammarly to help with this.
> 
> kindly fix those issues and submit your project for another review
> 
> ### If you have any question kindly reach me on slack @peterrobert
> ### HAPPY CODING

Hello Peter,
I will request another code review just to make sure that my database is not working because I do not understand why it is not working since I declared my friendship table only once!

**Review by PhillipUg — CHANGES_REQUESTED** [review]
Hey team, 👋

You have done an amazing job implementing the requirements for this project.

However, there are still some changes 👇 you need to implement to approve this request 🔍

### Changes Required ♻️ 

- [ ] Mention in your `README.md` under **setup** that users should run `yarn` to install some missing packages. This caused your app to crash while I was setting it up
- [ ] You have two failing tests when I run `RSpec`.

#### Please, make all REQUIRED changes and submit your request again! 😀

If you have any questions, feel free to send me a message through Slack as **Phillip Musiime**
I would be happy to help! 👩‍💻 

Happy coding 🤓

**Review by PhillipUg — APPROVED** [review]
# Status: Project Approved! 🥇 
Congratulations on implementing all requirements and getting this project approved. :+1:

You can merge this branch into the development branch when you're ready and go on to your next project.
:bulb:  Do not forget to submit your project completion form after merging this branch.

All the best team,

For any assistance, you can contact me on slack as **Phillip Musiime**

**Pull request merged**
